### ISSUE TITLE
I tried getting these updated files (Linux kernel and U-Boot) from LEGO customer support recently. Supposedly they are working on making these available, but it is a slow process.

### ISSUE THREAD

**Issue by qiux7hyun** [mindboards/ev3sources#43]
I tried getting these updated files (Linux kernel and U-Boot) from LEGO customer support recently. Supposedly they are working on making these available, but it is a slow process.

_Originally posted by @dlech in https://github.com/mindboards/ev3sources/issues/42#issuecomment-415775397_

do you get the sources , Would you mind to send me a note, when you got the sources?

**Comment by dlech** [comment]
Nope, still waiting. I think @JakubVanek hasn't had any luck either.

**Comment by JakubVanek** [comment]
Yep, I tried to obtain the source code for 1.10E firmware version in March 2020, but I wasn't successful with that. ~Some older kernel/u-boot revisions are available in the [extended](https://github.com/mindboards/ev3sources-xtended/tree/master/ev3sources/extra) repository though, and I believe the `EV3os.tar.bz2` archive mentioned in #42 is present in the [latest 1.09 sources](https://le-www-live-s.legocdn.com/sc/media/files/ev3-developer-kit/lego-mindstorms-ev3-firmware-source-code-d7a19f70086183fc82354f8de659a2da.bz2) as the file `open_first/lmsfs_with_telnet.tar.bz2`.~ Nevermind, `EV3os.tar.bz2` should have contained the updated source code of kernel and u-boot, this is not available anywhere AFAIK.

**Comment by mrdc** [comment]
> Nevermind, `EV3os.tar.bz2` should have contained the updated source code of kernel and u-boot

Hi, any update on this? I’ve made 2 kernel modules (from different sources) for Edimax Un7811 v2 (which is not supported by original firmwares), but it’s builded for the old 1.04/1.05 firmware. So, I’m not sure that it will work on the latest 1.09H/1.10E (will test later). BTW looks like 1.09H and 1.10E have minimal differences: the first is for Home Edition (31313 set) and the second for Education (45544 set).

**Comment by JakubVanek** [comment]
Hi, I unfortunately do not remember LEGO giving me any feedback apart from that they were aware of the issue. However, I wouldn't rule out that some update got lost in my inbox, so I don't really know what is the current status of this.

**Comment by mrdc** [comment]
> Hi, I unfortunately do not remember LEGO giving me any feedback apart from that they were aware of the issue. However, I wouldn't rule out that some update got lost in my inbox, so I don't really know what is the current status of this.

Hi, thanks. Then I’ll try to compile the latest source code using the old kernel we have.
Uboot tools, mkimage etc are installed separately, so I think only the kernel can affect the building process. Diff shouldn’t be too large between 1.09 and 1.05 which we have.

**Comment by mrdc** [comment]
Well, I've made some tests: it fails to build but overall looks not bad :D
v109D uses the same kernel & uboot versions as v105D (at least it stated in build files).
Errors when building the kernel:
```
drivers/net/wireless/b43/main.c:3752: error: 'struct ieee80211_key_conf' has no member named 'alg'
drivers/net/wireless/b43/main.c:3753: error: 'ALG_WEP' undeclared (first use in this function)
drivers/net/wireless/b43/main.c:3753: error: (Each undeclared identifier is reported only once
drivers/net/wireless/b43/main.c:3753: error: for each function it appears in.)
drivers/net/wireless/b43/main.c:3759: error: 'ALG_TKIP' undeclared (first use in this function)
drivers/net/wireless/b43/main.c:3762: error: 'ALG_CCMP' undeclared (first use in this function)
drivers/net/wireless/b43/main.c:4399: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4400: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4401: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4402: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4403: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4410: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4414: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4415: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4416: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4436: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4441: error: dereferencing pointer to incomplete type
drivers/net/wireless/b43/main.c:4582: error: unknown field 'get_tx_stats' specified in initializer
drivers/net/wireless/b43/main.c:4906: error: 'IEEE80211_HW_NOISE_DBM' undeclared (first use in this function)
net/mac80211/driver-ops.h:42: error: dereferencing pointer to incomplete type
net/mac80211/driver-ops.h:42: error: dereferencing pointer to incomplete type
net/mac80211/driver-ops.h:50: error: dereferencing pointer to incomplete type
net/mac80211/driver-ops.h:50: error: dereferencing pointer to incomplete type
net/mac80211/driver-ops.h:78: error: too many arguments to function 'local->ops->prepare_multicast'
net/mac80211/driver-ops.h:125: error: too few arguments to function 'local->ops->update_tkip_key'
net/mac80211/driver-ops.h:132: error: too few arguments to function 'local->ops->hw_scan'
net/mac80211/driver-ops.h:204: error: 'const struct ieee80211_ops' has no member named 'get_tx_stats'
net/mac80211/rate.h:49: error: 'IEEE80211_TX_INTFL_RCALGO' undeclared (first use in this function)
net/mac80211/rate.h:49: error: (Each undeclared identifier is reported only once
net/mac80211/rate.h:49: error: for each function it appears in.)
net/mac80211/rate.h:80: error: too few arguments to function 'ref->ops->rate_update'
net/mac80211/main.c:261: error: implicit declaration of function 'ieee80211_stop_tx_ba_cb'
net/mac80211/main.c:267: error: implicit declaration of function 'ieee80211_start_tx_ba_cb'
```

**Comment by CE1CECL** [comment]
Any updates? I tried contacting LEGO yesterday (live chat) and they said someone will email me back, but I don't know how long it will take, if it will happen at all.

**Comment by CE1CECL** [comment]
Got a reply!

[LEGO Service 09385791.zip](https://github.com/user-attachments/files/19434855/LEGO.Service.09385791.zip)

**Comment by CE1CECL** [comment]
My reply back:

[LEGO Service 09385791 (2).zip](https://github.com/user-attachments/files/19435415/LEGO.Service.09385791.2.zip)

**Comment by CE1CECL** [comment]
[LEGO Service 09385791 (3).zip](https://github.com/user-attachments/files/19467814/LEGO.Service.09385791.3.zip)

**Comment by dlech** [comment]
Unfortunate, but that is a fair answer. The GPL does say that the offer to obtain the source code only has to be valid for 3 years and not forever.

**Comment by CE1CECL** [comment]
> Unfortunate, but that is a fair answer. The GPL does say that the offer to obtain the source code only has to be valid for 3 years and not forever.

3 years after the device is released or 3 years after the firmware version is released? Because these issues have been here since 2018.

**Comment by CE1CECL** [comment]
> > Unfortunate, but that is a fair answer. The GPL does say that the offer to obtain the source code only has to be valid for 3 years and not forever.
> 
> 3 years after the device is released or 3 years after the firmware version is released? Because these issues have been here since 2018.

[LME-EV3_Firmware_1.10E.zip](https://github.com/user-attachments/files/19469930/LME-EV3_Firmware_1.10E.zip)
The only reference to the latest compile date was here:
![Image](https://github.com/user-attachments/assets/48227400-2ccc-4566-8817-b3df70453cc9)
March 5th, 2018, issue https://github.com/mindboards/ev3sources/issues/42 was created on August 28, 2018, 5 months after the last firmware release they made ever, that being 1.10E. 
While 1.09D (the version prior) was released on March 8th, 2016
[lego-mindstorms-ev3-firmware-109d-developer-edition.zip](https://github.com/user-attachments/files/19469988/lego-mindstorms-ev3-firmware-109d-developer-edition.zip)
![Image](https://github.com/user-attachments/assets/518de59b-4903-4789-a64f-2fb9e694927a)

**Comment by JakubVanek** [comment]
I have found some indications that Lego maybe even internally has some mess in the source code. In PR https://github.com/c4ev3/ev3duder/pull/47, I found that firmware 1.10E does not initialize the U-Boot environment block at flash address 0x40000, while firmware 1.09E and earlier do. It seems that U-Boot was recompiled for the 1.10E release, while it was not recompiled for earlier ones (I suppose that the `open_first/uBoot` binary in the lms2012 source tarball was used for 1.09E and earlier). There are also some weird differences in the default U-Boot environment configuration:
- Commit https://github.com/mindboards/ev3sources/commit/d7e770bd22aa49ba81cf8c1eef7c3facf16cec6b indicates that some early firmwares used a `loadaddr=0xC0700000` configuration for U-Boot and that some early code released by LEGO contained that address.
- Firmwares 1.03E - 1.09E have `loadaddr=0xC0007FC0`.
- Firmware 1.10E has `loadaddr=0xC0700000`, i.e. the old value.

Similar differences can be observed in the `flashargs` variable.
